name = "syspatch_feed"
main = "build/worker/shim.mjs"
workers_dev = true
compatibility_date = "2022-01-20"
send_metrics = false

[vars]
WORKERS_RS_VERSION = "0.0.12"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration

[triggers]
crons = ["0 */2 * * *"]